export const paketan = [
    {
        id: 1,
        title: "Reguler",
        price: "____________________________",
        desc: "Cuci",
        desc2: "Setrika",
        desc3: "Packing",
        desc4: "Waktu",
        const: "Rp. 6000 / Kg",
    },
    {
        id: 2,
        title: "Reguler (Tanpa Setrika)",
        price: "____________________________",
        desc: "Cuci",
        desc2: "Setrika",
        desc3: "Packing",
        desc4: "Waktu",
        const: "Rp. 4500 / Kg",
    },
    {
        id: 3,
        title: "Paket 1 Hari",
        price: "____________________________",
        desc: "Cuci",
        desc2: "Setrika",
        desc3: "Packing",
        desc4: "Waktu",
        const: "Rp. 8000 / Kg",
    },
    {
        id: 4,
        title: "Paket Kilat",
        price: "_____________________________",
        desc: "Cuci",
        desc2: "Setrika",
        desc3: "Packing",
        desc4: "Waktu",
        const: "Rp. 10.000 / Kg",
    },
]